[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CircularArrayBuffers = "9de3a189-e0c0-4e15-ba3b-b14b9fb0aec1"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Kaleido_jll = "f7e6163d-2fa5-5f23-b69c-1db539e41963"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RL = "88435259-3afc-4bfc-953c-ee5a97e5c988"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[compat]
Kaleido_jll = "0.1"
